# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\Program\default.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 307)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.delay_spinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delay_spinBox.sizePolicy().hasHeightForWidth())
        self.delay_spinBox.setSizePolicy(sizePolicy)
        self.delay_spinBox.setObjectName("delay_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.delay_spinBox)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.sleep_spinBox = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sleep_spinBox.sizePolicy().hasHeightForWidth())
        self.sleep_spinBox.setSizePolicy(sizePolicy)
        self.sleep_spinBox.setObjectName("sleep_spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.sleep_spinBox)
        self.ndetectors_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.ndetectors_spinBox.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ndetectors_spinBox.sizePolicy().hasHeightForWidth())
        self.ndetectors_spinBox.setSizePolicy(sizePolicy)
        self.ndetectors_spinBox.setObjectName("ndetectors_spinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ndetectors_spinBox)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.file_lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.file_lineEdit.setEnabled(False)
        self.file_lineEdit.setObjectName("file_lineEdit")
        self.gridLayout.addWidget(self.file_lineEdit, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.browse_pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.browse_pushButton.setObjectName("browse_pushButton")
        self.gridLayout.addWidget(self.browse_pushButton, 0, 3, 1, 1)
        self.time_checkBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.time_checkBox.setChecked(True)
        self.time_checkBox.setObjectName("time_checkBox")
        self.gridLayout.addWidget(self.time_checkBox, 1, 0, 1, 1)
        self.coincidence_spinBox = QtWidgets.QSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.coincidence_spinBox.sizePolicy().hasHeightForWidth())
        self.coincidence_spinBox.setSizePolicy(sizePolicy)
        self.coincidence_spinBox.setObjectName("coincidence_spinBox")
        self.gridLayout.addWidget(self.coincidence_spinBox, 4, 1, 1, 1)
        self.sampling_box = QtWidgets.QComboBox(self.groupBox_2)
        self.sampling_box.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sampling_box.setObjectName("sampling_box")
        self.gridLayout.addWidget(self.sampling_box, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.widget)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.ndetectors_spinBox, self.delay_spinBox)
        Dialog.setTabOrder(self.delay_spinBox, self.sleep_spinBox)
        Dialog.setTabOrder(self.sleep_spinBox, self.file_lineEdit)
        Dialog.setTabOrder(self.file_lineEdit, self.browse_pushButton)
        Dialog.setTabOrder(self.browse_pushButton, self.time_checkBox)
        Dialog.setTabOrder(self.time_checkBox, self.coincidence_spinBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Default properties"))
        self.groupBox.setTitle(_translate("Dialog", "Detectors"))
        self.label_2.setText(_translate("Dialog", "Number of detectors:"))
        self.label_3.setText(_translate("Dialog", "Delay time (ns):"))
        self.label_4.setText(_translate("Dialog", "Sleep time (ns):"))
        self.groupBox_2.setTitle(_translate("Dialog", "General"))
        self.label_6.setText(_translate("Dialog", "Sampling time: "))
        self.label_7.setText(_translate("Dialog", "Coincidence window time (ns):"))
        self.label_5.setText(_translate("Dialog", "File name:"))
        self.browse_pushButton.setText(_translate("Dialog", "Browse"))
        self.time_checkBox.setText(_translate("Dialog", "Include date time to name."))

