# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\Installer\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.logo_label = QtWidgets.QLabel(self.frame_2)
        self.logo_label.setObjectName("logo_label")
        self.horizontalLayout_2.addWidget(self.logo_label)
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.name_label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name_label.sizePolicy().hasHeightForWidth())
        self.name_label.setSizePolicy(sizePolicy)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.license_PlainText = QtWidgets.QPlainTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.license_PlainText.sizePolicy().hasHeightForWidth())
        self.license_PlainText.setSizePolicy(sizePolicy)
        self.license_PlainText.setMinimumSize(QtCore.QSize(250, 0))
        self.license_PlainText.setObjectName("license_PlainText")
        self.verticalLayout.addWidget(self.license_PlainText)
        self.destination_Box = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.destination_Box.sizePolicy().hasHeightForWidth())
        self.destination_Box.setSizePolicy(sizePolicy)
        self.destination_Box.setObjectName("destination_Box")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.destination_Box)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.destination_lineEdit = QtWidgets.QLineEdit(self.destination_Box)
        self.destination_lineEdit.setObjectName("destination_lineEdit")
        self.horizontalLayout.addWidget(self.destination_lineEdit)
        self.destination_Button = QtWidgets.QPushButton(self.destination_Box)
        self.destination_Button.setObjectName("destination_Button")
        self.horizontalLayout.addWidget(self.destination_Button)
        self.verticalLayout.addWidget(self.destination_Box)
        self.shortcuts_Box = QtWidgets.QGroupBox(self.frame)
        self.shortcuts_Box.setObjectName("shortcuts_Box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.shortcuts_Box)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.desktop_checkBox = QtWidgets.QCheckBox(self.shortcuts_Box)
        self.desktop_checkBox.setChecked(True)
        self.desktop_checkBox.setObjectName("desktop_checkBox")
        self.verticalLayout_3.addWidget(self.desktop_checkBox)
        self.startmenu_checkBox = QtWidgets.QCheckBox(self.shortcuts_Box)
        self.startmenu_checkBox.setChecked(True)
        self.startmenu_checkBox.setObjectName("startmenu_checkBox")
        self.verticalLayout_3.addWidget(self.startmenu_checkBox)
        self.verticalLayout.addWidget(self.shortcuts_Box)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.progress_label = QtWidgets.QLabel(self.frame)
        self.progress_label.setText("")
        self.progress_label.setObjectName("progress_label")
        self.verticalLayout.addWidget(self.progress_label)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Install Reimagined Quantum"))
        self.logo_label.setText(_translate("Dialog", "TextLabel"))
        self.name_label.setText(_translate("Dialog", "TextLabel"))
        self.destination_Box.setTitle(_translate("Dialog", "Destination Folder"))
        self.destination_Button.setText(_translate("Dialog", "Browse..."))
        self.shortcuts_Box.setTitle(_translate("Dialog", "Shortcuts"))
        self.desktop_checkBox.setText(_translate("Dialog", "Create desktop shortcut."))
        self.startmenu_checkBox.setText(_translate("Dialog", "Create start menu shortcut."))

