# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI\MainWindow\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 716)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_as_label = QtWidgets.QLabel(self.frame)
        self.save_as_label.setObjectName("save_as_label")
        self.horizontalLayout.addWidget(self.save_as_label)
        self.save_as_lineEdit = QtWidgets.QLineEdit(self.frame)
        self.save_as_lineEdit.setObjectName("save_as_lineEdit")
        self.horizontalLayout.addWidget(self.save_as_lineEdit)
        self.save_as_button = QtWidgets.QPushButton(self.frame)
        self.save_as_button.setObjectName("save_as_button")
        self.horizontalLayout.addWidget(self.save_as_button)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings_groupBox = QtWidgets.QGroupBox(self.frame_4)
        self.settings_groupBox.setMinimumSize(QtCore.QSize(240, 0))
        self.settings_groupBox.setObjectName("settings_groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.settings_groupBox)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.sampling_label = QtWidgets.QLabel(self.settings_groupBox)
        self.sampling_label.setObjectName("sampling_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.sampling_label)
        self.sampling_comboBox = QtWidgets.QComboBox(self.settings_groupBox)
        self.sampling_comboBox.setObjectName("sampling_comboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sampling_comboBox)
        self.coincidence_spinBox = QtWidgets.QSpinBox(self.settings_groupBox)
        self.coincidence_spinBox.setObjectName("coincidence_spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.coincidence_spinBox)
        self.delay_A_spinBox = QtWidgets.QSpinBox(self.settings_groupBox)
        self.delay_A_spinBox.setObjectName("delay_A_spinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.delay_A_spinBox)
        self.delay_B_spinBox = QtWidgets.QSpinBox(self.settings_groupBox)
        self.delay_B_spinBox.setObjectName("delay_B_spinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.delay_B_spinBox)
        self.sleep_A_spinBox = QtWidgets.QSpinBox(self.settings_groupBox)
        self.sleep_A_spinBox.setObjectName("sleep_A_spinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.sleep_A_spinBox)
        self.sleep_B_spinBox = QtWidgets.QSpinBox(self.settings_groupBox)
        self.sleep_B_spinBox.setObjectName("sleep_B_spinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.sleep_B_spinBox)
        self.coincidence_label = QtWidgets.QLabel(self.settings_groupBox)
        self.coincidence_label.setObjectName("coincidence_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.coincidence_label)
        self.delay_A_label = QtWidgets.QLabel(self.settings_groupBox)
        self.delay_A_label.setObjectName("delay_A_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.delay_A_label)
        self.delay_B_label = QtWidgets.QLabel(self.settings_groupBox)
        self.delay_B_label.setObjectName("delay_B_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.delay_B_label)
        self.sleep_A_label = QtWidgets.QLabel(self.settings_groupBox)
        self.sleep_A_label.setObjectName("sleep_A_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.sleep_A_label)
        self.sleep_B_label = QtWidgets.QLabel(self.settings_groupBox)
        self.sleep_B_label.setObjectName("sleep_B_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.sleep_B_label)
        self.lock_settings_button = QtWidgets.QPushButton(self.settings_groupBox)
        self.lock_settings_button.setObjectName("lock_settings_button")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lock_settings_button)
        self.verticalLayout_3.addWidget(self.settings_groupBox)
        self.connect_button = QtWidgets.QPushButton(self.frame_4)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_3.addWidget(self.connect_button)
        self.acquisition_button = QtWidgets.QPushButton(self.frame_4)
        self.acquisition_button.setObjectName("acquisition_button")
        self.verticalLayout_3.addWidget(self.acquisition_button)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.tabWidget = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget.setObjectName("tabWidget")
        self.historical_tab = QtWidgets.QWidget()
        self.historical_tab.setObjectName("historical_tab")
        self.tabWidget.addTab(self.historical_tab, "")
        self.current_tab = QtWidgets.QWidget()
        self.current_tab.setObjectName("current_tab")
        self.tabWidget.addTab(self.current_tab, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.frame_2)
        self.plots_frame = QtWidgets.QFrame(self.centralWidget)
        self.plots_frame.setMinimumSize(QtCore.QSize(0, 260))
        self.plots_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plots_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plots_frame.setObjectName("plots_frame")
        self.verticalLayout.addWidget(self.plots_frame)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 544, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionSave_as)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Abacus Software"))
        self.save_as_label.setText(_translate("MainWindow", "Save as:"))
        self.save_as_button.setText(_translate("MainWindow", "Open"))
        self.settings_groupBox.setTitle(_translate("MainWindow", "Settings"))
        self.sampling_label.setText(_translate("MainWindow", "Sampling time:"))
        self.coincidence_label.setText(_translate("MainWindow", "Coincidence window (ns):"))
        self.delay_A_label.setText(_translate("MainWindow", "Delay A (ns):"))
        self.delay_B_label.setText(_translate("MainWindow", "Delay B (ns):"))
        self.sleep_A_label.setText(_translate("MainWindow", "Sleep time A (ns):"))
        self.sleep_B_label.setText(_translate("MainWindow", "Sleep time B (ns):"))
        self.lock_settings_button.setText(_translate("MainWindow", "Lock settings"))
        self.connect_button.setText(_translate("MainWindow", "Connect"))
        self.acquisition_button.setText(_translate("MainWindow", "Start acquisition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.historical_tab), _translate("MainWindow", "Historical data"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.current_tab), _translate("MainWindow", "Current data"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

